### ISSUE TITLE
FastQC: Java Thread exception: internal language error

### ISSUE THREAD

**Issue by florianzwagemaker** [DennisSchmitz/Jovian_archive#135]
FastQC has gotten a habit of throwing a "Thread exception" error for certain datasets without obvious or clear indication.

This issue is most likely related to issue #78 

The error itself is as follows:
```
Exception in thread "Thread-1" java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.desktop/sun.font.SunFontManager.getInstance(SunFontManager.java:251)
	at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
	at java.desktop/sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:856)
	at uk.ac.babraham.FastQC.Graphs.QualityBoxPlot.paint(QualityBoxPlot.java:88)
	at java.desktop/javax.swing.JComponent.print(JComponent.java:1221)
	at uk.ac.babraham.FastQC.Modules.AbstractQCModule.writeDefaultImage(AbstractQCModule.java:68)
	at uk.ac.babraham.FastQC.Modules.PerBaseQualityScores.makeReport(PerBaseQualityScores.java:199)
	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:131)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:178)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:110)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
	... 13 more
Caused by: java.lang.NullPointerException
	at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1288)
	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
	at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:765)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:440)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:385)
	at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
	... 18 more
```

There's no clear indication that this issue is OS-specific or dataset-specific

**Comment by florianzwagemaker** [comment]
This issue *appears* to be resolved with the following commit: https://github.com/DennisSchmitz/Jovian/commit/d3e0d4cca71fd98ff62135e7fa4e969e67c61b0f

Changing the openJDK version to `10.0.2` in the conda environment seems to solve this issue as FastQC no longer throws this exception and creates the necessary files without issue.

OpenJDK version `11.*` cannot be used for this matter as Trimmomatic appears to be incompatible (?)
However, version `10.0.2` seems to work just fine thusfar.

Requires further testing before merging into master however
