### ISSUE TITLE
draw_heatmaps error: max() arg is an empty sequence

### ISSUE THREAD

**Issue by florianzwagemaker** [DennisSchmitz/Jovian_archive#42]
full output from draw_heatmaps.log

```
These are the arguments you have provided:
  INPUT:
classified = results/all_taxClassified.tsv,
numbers = results/multiqc_data/multiqc_trimmomatic.txt
  OUTPUT:
super = results/heatmaps/Superkingdoms_heatmap.html
virus = ['results/heatmaps/Virus_heatmap.html']
phage = ['results/heatmaps/Phage_heatmap.html']
bact = ['results/heatmaps/Bacteria_heatmap.html']
super_quantities = results/Superkingdoms_quantities_per_sample.csv
stats = results/Taxonomic_rank_statistics.tsv
vir_stats = results/Virus_rank_statistics.tsv
phage_stats = results/Phage_rank_statistics.tsv
bact_stats = results/Bacteria_rank_statistics.tsv
  OPTIONAL PARAMETERS:
colour = ['#000000']

File results/Superkingdoms_quantities_per_sample.csv has been created!
File results/Taxonomic_rank_statistics.tsv has been created!
File results/Virus_rank_statistics.tsv has been created!
File results/Phage_rank_statistics.tsv has been created!
File results/Bacteria_rank_statistics.tsv has been created!
The heatmap Superkingdoms heatmap has been created and written to: results/heatmaps/Superkingdoms_heatmap.html
The heatmap Virus order heatmap has been created and written to: results/heatmaps/Virus_heatmap-order.html
The heatmap Virus family heatmap has been created and written to: results/heatmaps/Virus_heatmap-family.html
The heatmap Virus genus heatmap has been created and written to: results/heatmaps/Virus_heatmap-genus.html
The heatmap Virus species heatmap has been created and written to: results/heatmaps/Virus_heatmap-species.html
The heatmap Phage order heatmap has been created and written to: results/heatmaps/Phage_heatmap-order.html
The heatmap Phage family heatmap has been created and written to: results/heatmaps/Phage_heatmap-family.html
The heatmap Phage genus heatmap has been created and written to: results/heatmaps/Phage_heatmap-genus.html
Traceback (most recent call last):
  File "bin/draw_heatmaps.py", line 565, in <module>
    main()
  File "bin/draw_heatmaps.py", line 549, in main
    colour=arguments.colour)
  File "bin/draw_heatmaps.py", line 336, in draw_heatmaps
    max_load = max(percent_of_total)
ValueError: max() arg is an empty sequence
```

From DRMAA log:
```
[Mon May 13 09:25:19 2019]
rule draw_heatmaps:
    input: results/all_taxClassified.tsv, results/multiqc_data/multiqc_trimmomatic.txt
    output: results/Superkingdoms_quantities_per_sample.csv, results/heatmaps/Superkingdoms_heatmap.html, results/heatmaps/Virus_heatmap-order.html, results/heatmaps/Virus_heatmap-family.html, results/heatmaps/Virus_heatmap-genus.html, results/heatmaps/Virus_heatmap-species.html, results/heatmaps/Phage_heatmap-order.html, results/heatmaps/Phage_heatmap-family.html, results/heatmaps/Phage_heatmap-genus.html, results/heatmaps/Phage_heatmap-species.html, results/heatmaps/Bacteria_heatmap-phylum.html, results/heatmaps/Bacteria_heatmap-class.html, results/heatmaps/Bacteria_heatmap-order.html, results/heatmaps/Bacteria_heatmap-family.html, results/heatmaps/Bacteria_heatmap-genus.html, results/heatmaps/Bacteria_heatmap-species.html, results/Taxonomic_rank_statistics.tsv, results/Virus_rank_statistics.tsv, results/Phage_rank_statistics.tsv, results/Bacteria_rank_statistics.tsv
    log: logs/draw_heatmaps.log
    jobid: 0
    benchmark: logs/benchmark/draw_heatmaps.txt

Activating conda environment: /data/BioGrid/zwagemaf/sispa-jovian-test-new/.snakemake/conda/d155695a
[Mon May 13 09:25:29 2019]
Error in rule draw_heatmaps:
    jobid: 0
    output: results/Superkingdoms_quantities_per_sample.csv, results/heatmaps/Superkingdoms_heatmap.html, results/heatmaps/Virus_heatmap-order.html, results/heatmaps/Virus_heatmap-family.html, results/heatmaps/Virus_heatmap-genus.html, results/heatmaps/Virus_heatmap-species.html, results/heatmaps/Phage_heatmap-order.html, results/heatmaps/Phage_heatmap-family.html, results/heatmaps/Phage_heatmap-genus.html, results/heatmaps/Phage_heatmap-species.html, results/heatmaps/Bacteria_heatmap-phylum.html, results/heatmaps/Bacteria_heatmap-class.html, results/heatmaps/Bacteria_heatmap-order.html, results/heatmaps/Bacteria_heatmap-family.html, results/heatmaps/Bacteria_heatmap-genus.html, results/heatmaps/Bacteria_heatmap-species.html, results/Taxonomic_rank_statistics.tsv, results/Virus_rank_statistics.tsv, results/Phage_rank_statistics.tsv, results/Bacteria_rank_statistics.tsv
    log: logs/draw_heatmaps.log
    conda-env: /data/BioGrid/zwagemaf/sispa-jovian-test-new/.snakemake/conda/d155695a

RuleException:
CalledProcessError in line 665 of /data/BioGrid/zwagemaf/sispa-jovian-test-new/Snakefile:
Command 'source /mnt/miniconda/bin/activate '/data/BioGrid/zwagemaf/sispa-jovian-test-new/.snakemake/conda/d155695a'; set -euo pipefail;  python bin/draw_heatmaps.py -c results/all_taxClassified.tsv -n results/multiqc_data/multiqc_trimmomatic.txt -sq results/Superkingdoms_quantities_per_sample.csv -st results/Taxonomic_rank_statistics.tsv -vs results/Virus_rank_statistics.tsv -ps results/Phage_rank_statistics.tsv -bs results/Bacteria_rank_statistics.tsv -s results/heatmaps/Superkingdoms_heatmap.html -v results/heatmaps/Virus_heatmap.html -p results/heatmaps/Phage_heatmap.html -b results/heatmaps/Bacteria_heatmap.html > logs/draw_heatmaps.log 2>&1' returned non-zero exit status 1.
  File "/data/BioGrid/zwagemaf/sispa-jovian-test-new/Snakefile", line 665, in __rule_draw_heatmaps
  File "/home/zwagemaf/.conda/envs/Jovian_master/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job draw_heatmaps since they might be corrupted:
results/Superkingdoms_quantities_per_sample.csv, results/heatmaps/Superkingdoms_heatmap.html, results/heatmaps/Virus_heatmap-order.html, results/heatmaps/Virus_heatmap-family.html, results/heatmaps/Virus_heatmap-genus.html, results/heatmaps/Virus_heatmap-species.html, results/heatmaps/Phage_heatmap-order.html, results/heatmaps/Phage_heatmap-family.html, results/heatmaps/Phage_heatmap-genus.html, results/Taxonomic_rank_statistics.tsv, results/Virus_rank_statistics.tsv, results/Phage_rank_statistics.tsv, results/Bacteria_rank_statistics.tsv
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

Not sure if directly related to #41

**Comment by samnooij** [comment]
Yes, this is the exact error that I also got while testing for Thierry. It happens with empty dataframes, i.e. when there are no contigs assigned to the taxon/rank for which it is trying to make a heatmap. This error should be tackled by https://github.com/DennisSchmitz/Jovian/commit/7c438f11917935ce71cb23f65d958abc3eab2ea9.

**Comment by florianzwagemaker** [comment]
Unfortunately, this error has returned in the current master branch aswell as the v0.9.5-dev branch.

For reproduction purposes: The used files were from the public Cameroon dataset. Samples SRR7892447 and SRR7892448

## Full draw_heatmaps.log output:

```
These are the arguments you have provided:
  INPUT:
classified = results/all_taxClassified.tsv,
numbers = results/multiqc_data/multiqc_trimmomatic.txt
  OUTPUT:
super = results/heatmaps/Superkingdoms_heatmap.html
virus = ['results/heatmaps/Virus_heatmap.html']
phage = ['results/heatmaps/Phage_heatmap.html']
bact = ['results/heatmaps/Bacteria_heatmap.html']
super_quantities = results/Superkingdoms_quantities_per_sample.csv
stats = results/Taxonomic_rank_statistics.tsv
vir_stats = results/Virus_rank_statistics.tsv
phage_stats = results/Phage_rank_statistics.tsv
bact_stats = results/Bacteria_rank_statistics.tsv
  OPTIONAL PARAMETERS:
colour = ['#000000']

File results/Superkingdoms_quantities_per_sample.csv has been created!
File results/Taxonomic_rank_statistics.tsv has been created!
File results/Virus_rank_statistics.tsv has been created!
File results/Phage_rank_statistics.tsv has been created!
File results/Bacteria_rank_statistics.tsv has been created!
Traceback (most recent call last):
  File "bin/draw_heatmaps.py", line 578, in <module>
    main()
  File "bin/draw_heatmaps.py", line 538, in main
    colour = arguments.colour)
  File "bin/draw_heatmaps.py", line 307, in draw_heatmaps
    max_load = max(percent_of_total)
ValueError: max() arg is an empty sequence
```

## DRMAA output:
```
Sender: LSF System <lsfadmin@rivm-lsfsv-l01p.rivm.ssc-campus.nl>
Subject: Job 366413: <Jovian_draw_heatmaps.jobid23> in cluster <RIVM-LSF-PRD> Exited

Job <Jovian_draw_heatmaps.jobid23> was submitted from host <rivm-biohn-l03p.int.ssc-campus.nl> by user <zwagemaf> in cluster <RIVM-LSF-PRD> at Wed Jul 17 15:54:14 2019.
Job was executed on host(s) <rivm-lsfsv-l01p.rivm.ssc-campus.nl>, in queue <bio>, as user <zwagemaf> in cluster <RIVM-LSF-PRD> at Wed Jul 17 15:54:14 2019.
</home/zwagemaf> was used as the home directory.
</mnt/scratch_dir/zwagemaf/Jovian> was used as the working directory.
Started at Wed Jul 17 15:54:14 2019.
Terminated at Wed Jul 17 15:54:29 2019.
Results reported at Wed Jul 17 15:54:29 2019.

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
/mnt/scratch_dir/zwagemaf/Jovian/.snakemake/tmp.sz8cckl6/Jovian_draw_heatmaps.jobid23
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   3.87 sec.
    Max Memory :                                 31 MB
    Average Memory :                             17.00 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   -
    Max Processes :                              7
    Max Threads :                                10
    Run time :                                   14 sec.
    Turnaround time :                            15 sec.

The output (if any) follows:

Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	draw_heatmaps
	1

[Wed Jul 17 15:54:21 2019]
rule draw_heatmaps:
    input: results/all_taxClassified.tsv, results/multiqc_data/multiqc_trimmomatic.txt
    output: results/Superkingdoms_quantities_per_sample.csv, results/heatmaps/Superkingdoms_heatmap.html, results/heatmaps/Virus_heatmap-order.html, results/heatmaps/Virus_heatmap-family.html, results/heatmaps/Virus_heatmap-genus.html, results/heatmaps/Virus_heatmap-species.html, results/heatmaps/Phage_heatmap-order.html, results/heatmaps/Phage_heatmap-family.html, results/heatmaps/Phage_heatmap-genus.html, results/heatmaps/Phage_heatmap-species.html, results/heatmaps/Bacteria_heatmap-phylum.html, results/heatmaps/Bacteria_heatmap-class.html, results/heatmaps/Bacteria_heatmap-order.html, results/heatmaps/Bacteria_heatmap-family.html, results/heatmaps/Bacteria_heatmap-genus.html, results/heatmaps/Bacteria_heatmap-species.html, results/Taxonomic_rank_statistics.tsv, results/Virus_rank_statistics.tsv, results/Phage_rank_statistics.tsv, results/Bacteria_rank_statistics.tsv
    log: logs/draw_heatmaps.log
    jobid: 0
    benchmark: logs/benchmark/draw_heatmaps.txt

Activating conda environment: /mnt/scratch_dir/zwagemaf/Jovian/.snakemake/conda/69287462
[Wed Jul 17 15:54:28 2019]
Error in rule draw_heatmaps:
    jobid: 0
    output: results/Superkingdoms_quantities_per_sample.csv, results/heatmaps/Superkingdoms_heatmap.html, results/heatmaps/Virus_heatmap-order.html, results/heatmaps/Virus_heatmap-family.html, results/heatmaps/Virus_heatmap-genus.html, results/heatmaps/Virus_heatmap-species.html, results/heatmaps/Phage_heatmap-order.html, results/heatmaps/Phage_heatmap-family.html, results/heatmaps/Phage_heatmap-genus.html, results/heatmaps/Phage_heatmap-species.html, results/heatmaps/Bacteria_heatmap-phylum.html, results/heatmaps/Bacteria_heatmap-class.html, results/heatmaps/Bacteria_heatmap-order.html, results/heatmaps/Bacteria_heatmap-family.html, results/heatmaps/Bacteria_heatmap-genus.html, results/heatmaps/Bacteria_heatmap-species.html, results/Taxonomic_rank_statistics.tsv, results/Virus_rank_statistics.tsv, results/Phage_rank_statistics.tsv, results/Bacteria_rank_statistics.tsv
    log: logs/draw_heatmaps.log
    conda-env: /mnt/scratch_dir/zwagemaf/Jovian/.snakemake/conda/69287462

RuleException:
CalledProcessError in line 707 of /mnt/scratch_dir/zwagemaf/Jovian/Snakefile:
Command 'source /mnt/miniconda/bin/activate '/mnt/scratch_dir/zwagemaf/Jovian/.snakemake/conda/69287462'; set -euo pipefail;  python bin/draw_heatmaps.py -c results/all_taxClassified.tsv -n results/multiqc_data/multiqc_trimmomatic.txt -sq results/Superkingdoms_quantities_per_sample.csv -st results/Taxonomic_rank_statistics.tsv -vs results/Virus_rank_statistics.tsv -ps results/Phage_rank_statistics.tsv -bs results/Bacteria_rank_statistics.tsv -s results/heatmaps/Superkingdoms_heatmap.html -v results/heatmaps/Virus_heatmap.html -p results/heatmaps/Phage_heatmap.html -b results/heatmaps/Bacteria_heatmap.html > logs/draw_heatmaps.log 2>&1' returned non-zero exit status 1.
  File "/mnt/scratch_dir/zwagemaf/Jovian/Snakefile", line 707, in __rule_draw_heatmaps
  File "/home/zwagemaf/.conda/envs/Jovian_master/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job draw_heatmaps since they might be corrupted:
results/Superkingdoms_quantities_per_sample.csv, results/Taxonomic_rank_statistics.tsv, results/Virus_rank_statistics.tsv, results/Phage_rank_statistics.tsv, results/Bacteria_rank_statistics.tsv
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by DennisSchmitz** [comment]
Fixed it in 7aa5cdbb, I think, @samnooij can you please double check.

**Comment by DennisSchmitz** [comment]
Another reason for this bug was the hardcoding of expected sample names (should contain "_R1"). This was turned into a regex in 7aa5cdb so I guess together with Sam's previous fix 7c438f1 this can be closed? 

Sam, can you double check and confirm?

**Comment by samnooij** [comment]
The code looks good. If it worked in your test, it should probably work in any case with sample names that contain 1/2 (with or without 'R') for paired-end reads.
I can test it when I come back from holidays, but I don't see this causing more bugs than before.

**Comment by DennisSchmitz** [comment]
Perfect, then I'll close this issue. Enjoy your holiday, and thx for checking the issue during it!
