### ISSUE TITLE
Typingtools are unstable and sometimes cannot cope with queries

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#51]
Related to #29 

We are reliant on the typingtool webservice for our virus typing. However, the webservice cannot cope with certain queries at certain times, i.e. it cannot handle large queries at a time that the service is under heavy load. A good example is when you analyse [SRA dataset "PRJNA491626"](https://www.ncbi.nlm.nih.gov/sra/?term=PRJNA491626); the Jovian pipeline finishes without error. However, when you try to do virus typing, somtimes, three (so far) replies from the webservice can occur...

1. It replies a valid xml file with correct typing results. Jovian is handle to process these, so, not a problem.

2. It replies a terse xml file with `502 Proxy Error`: 
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/mpf/typingservice/enterovirus/">POST&nbsp;/mpf/typingservice/enterovirus/</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
</body></html>
```

The typing tool replies with a verbose HTML file, stating:
```
<!DOCTYPE HTML PUBLIC "-//W3C//Dtd HTML 4.0 transitional//nl">
<html lang="nl">
    <head>
        <title>RIVM beveiligde toegang</title>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <link href="/nesp/images/hf_menu.css" rel="stylesheet"> 
        <link href="/nesp/images/HF_message.css" rel="stylesheet"> 
        <link href="/nesp/images/HF_obj_list_table.css" rel="stylesheet"> 
        <link href="/nesp/images/hf_style.css" rel="stylesheet"> 
          <style>
                /* * { margin: 0; padding: 0; } */
             /* #header         { background-image: url(/nesp/images/AMHeader_background.png); background-repeat: repeat-x; } */
              html body {
                        background-color: #F3F5F6;
                        text-align: center;
                        font-family: Verdana,Ariel,sans-serif;

                        }

              #wrapper {
                        margin: 0px auto; 
                        border: 0px solid pink;
                        width: 495px; height: 393px;
                        }


              #logo                     { position: absolute; top: 0px; right: 0px;     }   
              #title            { position: absolute; font-size: 1.2em; color: white; top: 13px; left: 55px; }
                #subtitle               { position: relative; font-size: .9em; color: black; white-space: nowrap; top: 0px; left: 0px; text-align: right; }
                #mcontent       { position: relative; padding: 5px; background-color: #fef1bc; }
                #content        { height: 200px; width: 100%; border: 0; margin: 0; padding: 0; overflow: none; height: 376px; background-color: #fef1bc;}
                #logoutbut              { position: absolute; top: 25px; right: 35px;   }
                #helpbutlogin   { position: absolute; color: yellow; top: 25px; right: 10px; }
                #loggingbut             { position: absolute; color: blue; top: 25px; right: 65px;      }

                .NLtab .tab1s   { background-color: #66959f; padding-left: 3px; padding-right: 8px; text-align: center; white-space: nowrap;   }
                .NLtab .tab1s a         { text-decoration: none; }
                .NLtab span.tab1s { padding:5; color: white; font-size: 0.9em; font-weight: bold; line-height: 17px; background-color: transparent; background-image: none; text-decoration: none; }
                .NLtab .tab1u   { background-color: #fef1bc; padding-left: 3px; padding-right: 3px; text-align: center; white-space: nowrap; border-left: 1px solid #fef1bc; border-right: 1px solid #fef1bc; border-top: 1px solid #fef1bc;          }
                .NLtab span.tab1u { border: none; padding:5; color: black; font-size: 0.8em; font-weight: bold; line-height: 17px; text-decoration: none; background-color: transparent;  }

                .NLtab tr.subtab td     {  color: white; padding: 2px }
                .NLtab tr.subtab a      { font-size: .8em; color: white; text-decoration: none; padding: 2px 5px 2px 5px}

                .selx   { border: 1px solid rgb(239, 238, 236); font-size: 1em; font-weight: bolder; background-repeat: repeat-x; background-position: 0pt bottom;}
                .unselx { border: 0px; font-size: .9em; font-weight: normal; background-image: none; }

body {
        margin : 0 0 0 0;
        margin-bottom: 0;
        margin-left : 0;
        margin-right : 0;
        margin-top : 0;
        background-color: #f3f5f6;
        font-family: Verdana, Arial, sans-serif;
}

.logintable {
        background-color:#f3f5f6;
        font:11px Verdana;
        font-weight:bold;
        color:#333333;
        /* background-image: url(bcgr_logo.gif); */
        background-repeat: no-repeat;
        height: 393px;
        width: 494px;
        background-image: url(/nesp/images/bcgr_logo.gif);
}

.message_info {
        margin-right: 25px;
        padding-right: 10px;
        padding-left: 34px;
        padding-bottom: 8px;
        padding-top: 8px;
        background-image: url(/nesp/images/message_info.gif);
        background-color: #fef1bc;
        background-repeat: no-repeat;
}

.if_body0 {
        background-color: #FEF1BC;
        text-align: center;
        font-family: Verdana,Ariel,sans-serif;
        font-weight: bold; font-size: 1em; letter-spacing: 0.1em; margin-top: 0.4em; margin-bottom: 0.4em; border-bottom: 2px solid #4D8593
}
.if_body {
        text-align: center;
}

        </style>

        <script>
               var g_curCard = null;            // initial displayed card
                 var g_cardContainer = null;    // div that holds all the authentication cards
                 var g_curSubtab = null;        // subtab currently displayed
                 var g_curTab = null;           // tab currently displayed

                 var menuItem = 0;
             function showHide(i)
             {
                 document.getElementById('menu1').style.display='none';
                 document.getElementById('menu2').style.display='none';
                 document.getElementById('submenu1').style.display='none';
                 document.getElementById('submenu2').style.display='none';
                 document.getElementById('menu' + i).style.display='block';
                 document.getElementById('submenu' + i).style.display='block';
                     if (i == 1)
                         switchContentPage("/nesp/jsp/content.jsp?sid=4");
                     else 
                         switchContentPage("/nesp/jsp/IdentityEditor.jsp?sid=4");
             }

                 function switchContentPage(newSrc)
                 {
                     parent.document.getElementById("content").src = newSrc;
                 }  

                 function onloadhandler()
                 {
                     g_cardContainer = document.getElementById("cardcontainer");
                     g_curSubtab           = document.getElementById("loginsubtab");
                     g_curTab        = document.getElementById("authtab");
                     g_curCard       = document.getElementById("selectedCard0");
                 }

                 function showhideTab(divid)
                 {
                     var element1 = document.getElementById(divid);

                     if(element1.style.display == "none")
                     {
                         element1.style.display = "block";
                           g_curTab.style.display = "none";

                         g_curTab = element1;
                     }
                 }

                 function subtabchange(divid)
                 {
                     var element1 = document.getElementById(divid);
                     var element2 = g_curSubtab;
                     element1.className = "selx";
                     if (element1.id != element2.id)
                     {
                         element2.className = "unselx";
                     }
                     g_curSubtab = element1;
                 }

                 function showHelp()
                 {
                     var helpURL = "login.html";
                 if (g_curSubtab.id == "fedsubtab")
                         helpURL = "/nesp/html/help/en/federations.html";

                 else if (g_curSubtab.id == "myprofile")
                           helpURL = "/nesp/html/help/en/myprofile.html";

                 else if (g_curSubtab.id == "sharing")
                           helpURL = "/nesp/html/help/en/sharing.html";

                 else if (g_curSubtab.id == "loginsubtab")
                           helpURL = "/nesp/html/help/en/userlogin.html";

                 else if (g_curSubtab.id == "newcardsubtab")
                           helpURL = "/nesp/html/help/en/newcard.html";

               else if (g_curSubtab.id == "logTicketsubtab")
                           helpURL = "/nesp/html/help/en/logticket.html";

                     var w;
                     w = window.open(helpURL, "nidsPopupHelp", "toolbar=no,location=no,directories=no,menubar=no,scrollbars=yes,resizable=yes,width=500,height=500");
                     if (w != null)
                     {
                          w.focus();
                     }
                 }
        </script>
    </head>

    <body onload="onloadhandler()">
        <div id="wrapper">
        <table width="100%" height="393" cellspacing="0" cellpadding="0" border="0" >
        <tr>
        <td valign="top"><br />
            <table class="logintable" height="393" width="494" border="0" cellspacing="0" cellpadding="0" align="center" valign="top">
               <tr valign="top">
                        <td width="24"><img src="/nesp/images/spacerrivm.gif" width="24" height="145" border="0"></td>
                        <td>&nbsp;</td>
                </tr>
                <tr valign="top">
                        <td width="24"><img src="/nesp/images/spacerrivm.gif" width="24" border="0"></td>
                        <td valign="top">
                <div id="StartDiv" style="display: block;" class="message_info">
                        <table border="0" width="80%"><tr><td>
                                <div class="head3b" align="center"><font size="4em">Bad Gateway!</font></div>
                        </td></tr></table>
                        <table border=0>
                            <tr>
                                <td>


    The proxy server received an invalid
    response from an upstream server.

  
    </p>
<p>

    The proxy server could not handle the request <em><a href="/mpf/typingservice/enterovirus/">POST&nbsp;/mpf/typingservice/enterovirus/</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p>
  
    
</td>
                </tr>
<tr height="100%"><td/></tr>
                </table>

                 </div>
                </tr>
        <!--    <tr valign="top">
                        <td width="24"><img src="/nesp/images/spacerrivm.gif" width="24" height="197" border="0"></td>
                        <td>&nbsp;</td>
                </tr> --> 
             </table>
        </td>
        </tr>
        </table>


        </div>
      <!--  <table width=100% border=0 cellpadding=0 cellspacing=0 bgcolor=#fef1bc >
            <tr>
                    <td>
                         <table cellspacing=0 width=100% border=0>
                              <tr>
                                    <td width=100%>      
                                        <div id="header"><img src="/nesp/images/bcgr_logo.gif"></div>    
                                        <div id="logo"><img src="/nesp/images/AMHeader_logo.png"></div>  
                                        <div id="title">NetIQ Access Manager</div>
                                    </td>
                                </tr>
                          </table> 
                    </td>
                </tr>
                <tr>
                    <td>
                        <table cellspacing=5 width=100%>
                              <tr>
                                    <td>
                                        


    <div id="mcontent">
  

    </div>

                                    </td>
                                </tr>
                          </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <table cellspacing=0 border=0 width=100%>
                              <tr>
                                    <td>
                                        <iframe scrolling=no id="content" src="/nesp/jsp/logoutSuccess.jsp?sid=4&sid=4" frameborder=0></iframe>
                                    </td>
                                </tr>
                          </table>
                    </td>
                </tr>
          </table> -->
    </body>
</html>
```

Case 2. and 3. will result in an errors like shown below in the parsing script:
```
Traceback (most recent call last):
  File "bin/typingtool_EV_XML_to_csv_parser.py", line 24, in <module>
	parsedXML = et.parse(INPUT_XML)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
	tree.parse(source, parser)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
	self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 49
```

For now, Jovian prints an error when case 2 and 3 occur. That error message redirects to this thread where we will post any updates. Important to know is that any sample that shows the error `Sample:    [sample_name]    Query cannot be handled by typingtool...` will be **omitted** from virus typing results. 

We have seen that these errors are somewhat stochastic, e.g. repeating them another time might work, we suspect this is due to the load on the web-services.

**Comment by DennisSchmitz** [comment]
Linked to issue #29, small update.

Apparently someone used a bot to continuously send queries... Hence all the proxy errors and overloading. That should be fixed now.

In the meanwhile, an improved version of the typingtools is online and being tested. Once testing is successful, it will replace the old version and then it should be much faster and more stable.

**Comment by DennisSchmitz** [comment]
Just an update: the new typing tool web-services are being tested and hopefully will come online after the holiday season.
