### ISSUE TITLE
Bug in heatmap script

### ISSUE THREAD

**Issue by alakob** [DennisSchmitz/Jovian_archive#70]
This error occurred when analyzing a small (20.000 reads) bacterial dataset. What is going on? 

```
Error in rule draw_heatmaps:
    jobid: 13
    output: results/Superkingdoms_quantities_per_sample.csv, results/heatmaps/Superkingdoms_heatmap.html, results/heatmaps/Virus_heatmap-order.html, results/heatmaps/Virus_heatmap-family.html, results/heatmaps/Virus_heatmap-genus.html, results/heatmaps/Virus_heatmap-species.html, results/heatmaps/Phage_heatmap-order.html, results/heatmaps/Phage_heatmap-family.html, results/heatmaps/Phage_heatmap-genus.html, results/heatmaps/Phage_heatmap-species.html, results/heatmaps/Bacteria_heatmap-phylum.html, results/heatmaps/Bacteria_heatmap-class.html, results/heatmaps/Bacteria_heatmap-order.html, results/heatmaps/Bacteria_heatmap-family.html, results/heatmaps/Bacteria_heatmap-genus.html, results/heatmaps/Bacteria_heatmap-species.html, results/Taxonomic_rank_statistics.tsv, results/Virus_rank_statistics.tsv, results/Phage_rank_statistics.tsv, results/Bacteria_rank_statistics.tsv
    log: logs/draw_heatmaps.log
    conda-env: /hps/nobackup/nucleotide/blaise/selecta/tools/jovian/Jovian_June_2019/Jovian/.snakemake/conda/4233129e

RuleException:
CalledProcessError in line 707 of /hps/nobackup/nucleotide/blaise/selecta/tools/jovian/Jovian_June_2019/Jovian/Snakefile:
Command 'source /hps/nobackup/nucleotide/blaise/selecta/tools/jovian/miniconda3/bin/activate '/hps/nobackup/nucleotide/blaise/selecta/tools/jovian/Jovian_June_2019/Jovian/.snakemake/conda/4233129e'; set -euo pipefail;  python bin/draw_heatmaps.py -c results/all_taxClassified.tsv -n results/multiqc_data/multiqc_trimmomatic.txt -sq results/Superkingdoms_quantities_per_sample.csv -st results/Taxonomic_rank_statistics.tsv -vs results/Virus_rank_statistics.tsv -ps results/Phage_rank_statistics.tsv -bs results/Bacteria_rank_statistics.tsv -s results/heatmaps/Superkingdoms_heatmap.html -v results/heatmaps/Virus_heatmap.html -p results/heatmaps/Phage_heatmap.html -b results/heatmaps/Bacteria_heatmap.html > logs/draw_heatmaps.log 2>&1' returned non-zero exit status 1.
  File "/hps/nobackup/nucleotide/blaise/selecta/tools/jovian/Jovian_June_2019/Jovian/Snakefile", line 707, in __rule_draw_heatmaps
  File "/hps/nobackup/nucleotide/blaise/selecta/tools/jovian/miniconda3/envs/Jovian_master/lib/python3.6/concurrent/futures/thread.py", line 56, in run


/hps/nobackup/nucleotide/blaise/selecta/tools/jovian/Jovian_June_2019/Jovian/.snakemake/conda/4233129e/lib/python3.7/site-packages/pandas/core/ops.py:1167: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

These are the arguments you have provided:
  INPUT:
classified = results/all_taxClassified.tsv,
numbers = results/multiqc_data/multiqc_trimmomatic.txt
  OUTPUT:
super = results/heatmaps/Superkingdoms_heatmap.html
virus = ['results/heatmaps/Virus_heatmap.html']
phage = ['results/heatmaps/Phage_heatmap.html']
bact = ['results/heatmaps/Bacteria_heatmap.html']
super_quantities = results/Superkingdoms_quantities_per_sample.csv
stats = results/Taxonomic_rank_statistics.tsv
vir_stats = results/Virus_rank_statistics.tsv
phage_stats = results/Phage_rank_statistics.tsv
bact_stats = results/Bacteria_rank_statistics.tsv
  OPTIONAL PARAMETERS:
colour = ['#000000']

File results/Superkingdoms_quantities_per_sample.csv has been created!
Traceback (most recent call last):
  File "bin/draw_heatmaps.py", line 578, in <module>
    main()
  File "bin/draw_heatmaps.py", line 512, in main
    virus_df = filter_taxa(df=merged_df, taxon="Viruses", rank="superkingdom")
  File "bin/draw_heatmaps.py", line 235, in filter_taxa
    subset_df = df[df[rank] == taxon]
  File "/hps/nobackup/nucleotide/blaise/selecta/tools/jovian/Jovian_June_2019/Jovian/.snakemake/conda/4233129e/lib/python3.7/site-packages/pandas/core/ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "/hps/nobackup/nucleotide/blaise/selecta/tools/jovian/Jovian_June_2019/Jovian/.snakemake/conda/4233129e/lib/python3.7/site-packages/pandas/core/ops.py", line 1169, in na_op
    raise TypeError("invalid type comparison")
TypeError: invalid type comparison
logs/draw_heatmaps.log (END)

```

**Comment by DennisSchmitz** [comment]
The reason this bug occurred is because the script still assumes that there are at least some virus scaffolds in the dataset, it's a remnant piece of code from an earlier version that was only intended for viromics datasets. We will push an update for it soon.

@samnooij, can you pick this up? Blaise has sent the fastq's to reproduce it via email. @alakob, in the meanwhile, this dataset does work: https://www.ncbi.nlm.nih.gov/sra/?term=PRJNA491626 . Since we cannot share our own data due to privacy concerns we use this public dataset, or parts thereof, to test Jovian outside the RIVM (we have no affiliation with the authors).

**Comment by samnooij** [comment]
Sorry to keep you waiting. Today I tested Jovian with the fastq files that Blaise sent on 7 June. Oddly enough the pipeline runs without any errors. Instead of creating heatmaps for viruses and phages it creates text files saying 'No contigs found for rank ...!', where '...' is the rank's name as in the file name (e.g. 'family'). This is also reported in `logs/draw_heatmaps.log`.
@alakob when did you last pull the code? (What version number?) It looks like you were using a relatively recent version. I'm not sure what is going on, but I will look into it further and in the meantime work on the enhancements from issues #37, #38 and #39. With 38 the current bug should also not be much of an issue anymore. It might still take a while though, as I spend most of my time on other projects.

**Comment by DennisSchmitz** [comment]
@alakob Have you tried it again, is it solved? Please let us know because I'm doing a cleanup of open issues and otherwise I'll close it.

**Comment by DennisSchmitz** [comment]
The heatmaps code has been thoroughly reworked by @samnooij, I'm closing this for now.
