### ISSUE TITLE
Render report notebook automatically

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#9]
Currently, all data generated by Jovian must be imported manually by opening the notebook and pressing the button `Run all`. Using `nbconvert` you can automatically render it, this could e.g. be added in the snakemake `onSucces` clause.

I tried this with an older version, but then there was a known bug between `nb_conda` and `Jupyter notebook` that caused this to fail. Have to check if current versions do allow automatic rendering.

**Comment by DennisSchmitz** [comment]
I am looking into it again, but, for sake of documentation, [this](https://stackoverflow.com/questions/35471894/can-i-run-jupyter-notebook-cells-in-commandline) is the solution but it runs into [this](https://github.com/Anaconda-Platform/nb_conda_kernels/issues/34) bug.

**Comment by DennisSchmitz** [comment]
The is the error:

```
(Jovian_master) [schmitzd@rivm-biohn-l01p dev_Jovian]$ jupyter nbconvert --to notebook --inplace --execute Notebook_report.ipynb
[NbConvertApp] WARNING | Config option `template_path` not recognized by `NotebookExporter`.
[NbConvertApp] Converting notebook Notebook_report.ipynb to notebook
Traceback (most recent call last):
  File "/home/schmitzd/.conda/envs/Jovian_master/bin/jupyter-nbconvert", line 10, in <module>
    sys.exit(main())
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 338, in start
    self.convert_notebooks()
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 508, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 479, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 408, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 379, in preprocess
    with self.setup_preprocessor(nb, resources, km=km):
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 324, in setup_preprocessor
    self.km, self.kc = self.start_new_kernel(cwd=path)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 271, in start_new_kernel
    km.start_kernel(extra_arguments=self.extra_arguments, **kwargs)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/jupyter_client/manager.py", line 246, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/jupyter_client/manager.py", line 170, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/home/schmitzd/.conda/envs/Jovian_master/lib/python3.6/site-packages/jupyter_client/kernelspec.py", line 236, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named conda-env-Jovian_master-py
```

Which leads to [this](https://github.com/jupyter/nbconvert/issues/515) issue, which doesn't seem to work...

**Comment by DennisSchmitz** [comment]
Still cannot get it to work properly, I'm changing to `wontfix` and closing issue.

**Comment by DennisSchmitz** [comment]
Fixed it by doing something completely different, I instead used `Initialization cells` module in  `nb_extension` and tagged all cells as `Initialization` cells. Now, when the notebook starts up, it automatically runs all cells. Added it in `0.9.4-dev`.
