### ISSUE TITLE
IGVjs does not install: "failed to download Chromium"

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#95]
One of the software components of `Jovian` is `IGVjs` and it handles the interactive scaffold alignment viewer in the web report. It is installed by jovian via `bash jovian -ic` or `bash jovian -ii`. However, at the RIVM the following error occurs:

**Problem:**

```
Succesfully activated Jovian_master environment
Installing IGVjs in your working directory...
This can take up to 15 minutes
check tools:
/mnt/scratch_dir/schmitzd/conda/envs/Jovian_master/bin/git OK
/mnt/scratch_dir/schmitzd/conda/envs/Jovian_master/bin/npm OK
/mnt/scratch_dir/schmitzd/conda/envs/Jovian_master/bin/nginx OK
/mnt/scratch_dir/schmitzd/conda/envs/Jovian_master/bin/node OK

Cloning into 'igv.js'...
remote: Enumerating objects: 102, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 27877 (delta 39), reused 33 (delta 11), pack-reused 27775
Receiving objects: 100% (27877/27877), 82.32 MiB | 25.44 MiB/s, done.
Resolving deltas: 100% (21718/21718), done.

Install all Node.js modules using npm (this can take a while...) output in npm_install_output and npm_install_output_err
test npm ping, ok
npm gave an error:
ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: write EPROTO 140584333535104:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:66:16)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/mnt/scratch_dir/schmitzd/Jovian_demo_20190916/bin/software/igv.js/node_modules/node-qunit-puppeteer/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/mnt/scratch_dir/schmitzd/Jovian_demo_20190916/bin/software/igv.js/node_modules/node-qunit-puppeteer/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11 errno: 'EPROTO', code: 'EPROTO', syscall: 'write' }
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Solution:**

This is due to a proxy setting error on our local server, if you do `unset http_proxy; unset https_proxy` and remove the `bin/software/igv.js` folder via `rm -rf bin/software/igv.js` and then install it again it will work properly.

**Comment by DennisSchmitz** [comment]
The IT department is aware of this problem and they will systematically remove these proxy variables during the next update. Until that time I'll leave this issue open.

**Comment by DennisSchmitz** [comment]
IT department updated the proxy settings, closing it.
